[workspace]
resolver = "2"

members = [
    "graphics",
    "compositor/primitive",
    "compositor/path",
    "compositor/box-2d",
    "compositor/text",
    "storyboard",
    "example",
    "visual-sample"
]
