[package]
name = "visual-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
storyboard = { path = "../storyboard" }

futures = "0.3.17"
