[package]
name = "storyboard-flex-layout"
version = "0.1.0"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2021"
license = "MIT"

[dependencies]
storyboard = { path = "../../core" }

stretch = "0.3.2"