[package]
name = "storyboard-box-2d"
version = "0.1.0"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2018"
license = "MIT"

[dependencies]
storyboard = { path = "../../core" }

bytemuck = { version = "1.7.2", features = [ "derive" ] }