[package]
name = "storyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
storyboard-core = { path = "../storyboard-core" }

winit = "0.26.1"
bytemuck = { version = "1.9.1", features = ["derive"] }
rustc-hash = "1.1.0"
instant = "0.1.12"
fontdue = "0.7.2"
rect_packer = "0.2.1"
ringbuffer = "0.8.4"
parking_lot = "0.12.1"
allsorts = "0.9.0"

[dev-dependencies]
pollster = "0.2.5"