[package]
name = "storyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
storyboard-graphics = { path = "../graphics" }

storyboard-primitive = { path = "../compositor/primitive" }
storyboard-path = { path = "../compositor/path" }
storyboard-box-2d = { path = "../compositor/box-2d" }

winit = "0.25.0"
