[package]
name = "storyboard-frame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
storyboard-render = { path = "../../crates/render" }
rustc-hash = "1.1.0"
indexmap = "1.9.1"
downcast = "0.11.0"
