[package]
name = "storyboard-path"
version = "0.1.0"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2021"
license = "MIT"

[dependencies]
storyboard-graphics = { path = "../../graphics" }

lyon = "0.17.5"
bytemuck = { version = "1.7.2", features = [ "derive" ] }